### ISSUE TITLE
arm64 link missing?

### ISSUE THREAD

**Issue by ItsLame** [MCMi460/OpenEmuRPC#4]
Can't seem to find link for arm64.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/37344470/205118426-d11a8d16-edca-4b70-be8f-bd098c5c27d5.png">

Using the x86_64 version displays this for me:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/37344470/205118717-7d2d18a5-e1e4-4898-837f-4c7b28d7b09b.png">

**Comment by MCMi460** [comment]
Thanks for bringing this to my attention!
This problem should now be fixed with [version 1.1](https://github.com/MCMi460/OpenEmuRPC/releases/tag/v1.1).
If you're having troubles launching the app, try to give it permissions like so:
** -> System Preferences -> Security and Privacy -> Screen Recording -> +**
...and choose the app's location.
