### ISSUE TITLE
Appears as "<no name>"

### ISSUE THREAD

**Issue by Habbinal** [MCMi460/OpenEmuRPC#5]
When I play a game on OpenEmu, it registers as "<no name>, <no name>, <no name>"

**Comment by Delation** [comment]
Agh, @MCMi460 please look at this repo again. It's breaking for a lot of people.
I don't remember from the last time that I've used this, but iirc, you said it would only display window names when they're in focus because of various permission limitations?
And look at #4, too. You forgot to remove the arm64 text from your default release text.

**Comment by MCMi460** [comment]
Sorry for taking so long to get to these issues!
And oh my goodness, this repo is a mess. I hate looking at code of mine from 2021 as it constantly reminds me that I was still learning Python at the time. (I didn't know what classes were)
As for this problem, it appears to be a permissions issue (as it most often always is!).
For whatever reason, past Mi460 thought it'd be a funny idea to make it only check once at the startup of the first time ever. I vaguely recall doing this because the `check_permissions()` function failed half of the time. Regardless, it isn't doing so now, so I'm just going to reformat the whole repository real quickly here and then post another release for like v1.1 or something to that extent.
Thanks for alerting me of this, @Delation, @Habbinal, and @ItsLame!

(P.S. I may or may not have just shaved off 100 lines of code)

**Comment by MCMi460** [comment]
This problem should now be fixed with [version 1.1](https://github.com/MCMi460/OpenEmuRPC/releases/tag/v1.1).

**Comment by MCMi460** [comment]
If you're having troubles launching the app, try to give it permissions like so:
** -> System Preferences -> Security and Privacy -> Screen Recording -> +**
...and choose the app's location.
